### ISSUE TITLE
Jekyll error in pathutil-0.16.2: no implicit conversion of Hash into Integer

### ISSUE THREAD

**Issue by kthoms** [karakun/karakun.github.io#184]
Running `docker-compose` leads to the following error:

```

docker-compose up
Starting karakungithubio_jekyll_1 ... done
Attaching to karakungithubio_jekyll_1
jekyll_1  | Using concurrent-ruby 1.1.7
jekyll_1  | Using i18n 0.9.5
jekyll_1  | Using minitest 5.14.2
jekyll_1  | Using thread_safe 0.3.6
jekyll_1  | Using tzinfo 1.2.8
jekyll_1  | Using zeitwerk 2.4.1
jekyll_1  | Using activesupport 6.0.3.4
jekyll_1  | Using public_suffix 3.1.1
jekyll_1  | Using addressable 2.7.0
jekyll_1  | Using bundler 2.2.16
jekyll_1  | Using coffee-script-source 1.11.1
jekyll_1  | Using execjs 2.7.0
jekyll_1  | Using coffee-script 2.4.1
jekyll_1  | Using colorator 1.1.0
jekyll_1  | Using ruby-enum 0.8.0
jekyll_1  | Using commonmarker 0.17.13
jekyll_1  | Using unf_ext 0.0.7.7
jekyll_1  | Using unf 0.1.4
jekyll_1  | Using simpleidn 0.1.1
jekyll_1  | Using dnsruby 1.61.5
jekyll_1  | Using eventmachine 1.2.7
jekyll_1  | Using http_parser.rb 0.6.0
jekyll_1  | Using em-websocket 0.5.2
jekyll_1  | Using ffi 1.13.1
jekyll_1  | Using ethon 0.12.0
jekyll_1  | Using multipart-post 2.1.1
jekyll_1  | Using ruby2_keywords 0.0.2
jekyll_1  | Using faraday 1.1.0
jekyll_1  | Using forwardable-extended 2.6.0
jekyll_1  | Using gemoji 3.0.1
jekyll_1  | Using sawyer 0.8.2
jekyll_1  | Using octokit 4.19.0
jekyll_1  | Using typhoeus 1.4.0
jekyll_1  | Using github-pages-health-check 1.16.1
jekyll_1  | Using rb-fsevent 0.10.4
jekyll_1  | Using rb-inotify 0.10.1
jekyll_1  | Using sass-listen 4.0.0
jekyll_1  | Using sass 3.7.4
jekyll_1  | Using jekyll-sass-converter 1.5.2
jekyll_1  | Using listen 3.3.0
jekyll_1  | Using jekyll-watch 2.2.1
jekyll_1  | Using rexml 3.2.4
jekyll_1  | Using kramdown 2.3.0
jekyll_1  | Using liquid 4.0.3
jekyll_1  | Using mercenary 0.3.6
jekyll_1  | Using pathutil 0.16.2
jekyll_1  | Using rouge 3.23.0
jekyll_1  | Using safe_yaml 1.0.5
jekyll_1  | Using jekyll 3.9.0
jekyll_1  | Using jekyll-avatar 0.7.0
jekyll_1  | Using jekyll-coffeescript 1.1.1
jekyll_1  | Using jekyll-commonmark 1.3.1
jekyll_1  | Using jekyll-commonmark-ghpages 0.1.6
jekyll_1  | Using jekyll-default-layout 0.1.4
jekyll_1  | Using jekyll-feed 0.15.1
jekyll_1  | Using jekyll-gist 1.5.0
jekyll_1  | Using jekyll-github-metadata 2.13.0
jekyll_1  | Using mini_portile2 2.4.0
jekyll_1  | Using nokogiri 1.10.10
jekyll_1  | Using html-pipeline 2.14.0
jekyll_1  | Using jekyll-mentions 1.6.0
jekyll_1  | Using jekyll-optional-front-matter 0.3.2
jekyll_1  | Using jekyll-paginate 1.1.0
jekyll_1  | Using jekyll-readme-index 0.3.0
jekyll_1  | Using jekyll-redirect-from 0.16.0
jekyll_1  | Using jekyll-relative-links 0.6.1
jekyll_1  | Using rubyzip 2.3.0
jekyll_1  | Using jekyll-remote-theme 0.4.2
jekyll_1  | Using jekyll-seo-tag 2.6.1
jekyll_1  | Using jekyll-sitemap 1.4.0
jekyll_1  | Using jekyll-swiss 1.0.0
jekyll_1  | Using jekyll-theme-architect 0.1.1
jekyll_1  | Using jekyll-theme-cayman 0.1.1
jekyll_1  | Using jekyll-theme-dinky 0.1.1
jekyll_1  | Using jekyll-theme-hacker 0.1.2
jekyll_1  | Using jekyll-theme-leap-day 0.1.1
jekyll_1  | Using jekyll-theme-merlot 0.1.1
jekyll_1  | Using jekyll-theme-midnight 0.1.1
jekyll_1  | Using jekyll-theme-minimal 0.1.1
jekyll_1  | Using jekyll-theme-modernist 0.1.1
jekyll_1  | Using jekyll-theme-primer 0.5.4
jekyll_1  | Using jekyll-theme-slate 0.1.1
jekyll_1  | Using jekyll-theme-tactile 0.1.1
jekyll_1  | Using jekyll-theme-time-machine 0.1.1
jekyll_1  | Using jekyll-titles-from-headings 0.5.3
jekyll_1  | Using jemoji 0.12.0
jekyll_1  | Using kramdown-parser-gfm 1.1.0
jekyll_1  | Using minima 2.5.1
jekyll_1  | Using unicode-display_width 1.7.0
jekyll_1  | Using terminal-table 1.8.0
jekyll_1  | Using github-pages 209
jekyll_1  | Bundle complete! 4 Gemfile dependencies, 91 gems now installed.
jekyll_1  | Use `bundle info [gemname]` to see where a bundled gem is installed.
jekyll_1  | Configuration file: /site/_config.yml
jekyll_1  |             Source: /site
jekyll_1  |        Destination: /site/_site
jekyll_1  |  Incremental build: disabled. Enable with --incremental
jekyll_1  |       Generating...
jekyll_1  |        Jekyll Feed: Generating feed for posts
jekyll_1  |                     done in 14.179 seconds.
jekyll_1  | /usr/local/bundle/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
jekyll_1  | 	from /usr/local/bundle/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read'
jekyll_1  | 	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:75:in `proc_version'
jekyll_1  | 	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:40:in `bash_on_windows?'
jekyll_1  | 	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:77:in `watch'
jekyll_1  | 	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:43:in `process'
jekyll_1  | 	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
jekyll_1  | 	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
jekyll_1  | 	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
jekyll_1  | 	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
jekyll_1  | 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
jekyll_1  | 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
jekyll_1  | 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
jekyll_1  | 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
jekyll_1  | 	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
jekyll_1  | 	from /usr/local/bundle/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
jekyll_1  | 	from /usr/local/bundle/bin/jekyll:23:in `load'
jekyll_1  | 	from /usr/local/bundle/bin/jekyll:23:in `<top (required)>'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
jekyll_1  | 	from /usr/local/bundle/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
jekyll_1  | 	from /usr/local/bundle/bin/bundle:23:in `load'
jekyll_1  | 	from /usr/local/bundle/bin/bundle:23:in `<main>'
jekyll_1  | jekyll 3.9.0 | Error:  no implicit conversion of Hash into Integer
```

**Comment by grigala** [comment]
I do not get the same error. Only a warning from `pathutil`:

![image](https://user-images.githubusercontent.com/2084794/116009006-6f7f3b80-a617-11eb-84f4-33e3f01b0b27.png)
